### ISSUE TITLE
llvm deobfuscator fail

### ISSUE THREAD

**Issue by ZakiG** [RPISEC/llvm-deobfuscator#1]
As you can see, there is a problem when we remove the confusion. How can we solve it
Errors is as follows:

`Call target 0x0 does not appear to be code in instruction at 0x4005ce
Function at 0x4005e0 is too large, skipping analysis
Analysis update took 0.050 seconds
Error fetching version list: Update authentication failed
Analysis update took 0.000 seconds
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/XXXXX/binaryninja/plugins/../python/binaryninja/plugin.py", line 420, in run
    self.task.run()
  File "/home/XXXXX/.binaryninja/plugins/llvm-deobfuscator-e7ec09ea4ae0d52ee9a4d28ff9f391c7efea2a57/__init__.py", line 16, in run
    self.func(bv, self.addr)
  File "/home/XXXXX/.binaryninja/plugins/llvm-deobfuscator-e7ec09ea4ae0d52ee9a4d28ff9f391c7efea2a57/deflatten.py", line 295, in deflatten_cfg
    state_var = func.get_low_level_il_at(addr).medium_level_il.dest
AttributeError: 'NoneType' object has no attribute 'medium_level_il'
`

Thanks

**Comment by krx** [comment]
@ZakiG could you provide the binary you're having this issue with?

**Comment by ZakiG** [comment]
Of course, this is the binary

Kareem El-Faramawi <notifications@github.com> 于2018年11月28日周三 上午3:35写道：

**Comment by krx** [comment]
Email attachments don't work with github, can you upload it somewhere and post a link?

**Comment by ZakiG** [comment]
OK, you can get binary from  here: https://transfer.sh/1OOtg/Interpreter

Kareem El-Faramawi <notifications@github.com> 于2018年11月28日周三 上午10:22写道：

**Comment by ZakiG** [comment]
Emmm, how can I solve this problem  finally ,thanks~

Kareem El-Faramawi <notifications@github.com> 于2018年11月29日周四 上午4:02写道：

**Comment by krx** [comment]
You should be able to just update the plugin and it'll be fixed, commit 88dcec9 fixes the issue. The problem was that binja wasn't fully analyzing the function, and this forces it to complete analysis.
